config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
    root 'static_pages#index' #<-  "name_controler#name_action" 
    get 'sobre', to: 'static_pages#about'
    get 'contato',to: 'static_pages#contact'
    get 'entrar', to: 'sessions#new'
    post 'entrar', to: 'sessions#create'
    get 'sair', to: 'sessions#destroy'

    resources :contacts
    resources :users, only: [:new,:create,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true, length: {maximum: 50}
    validates :phone, presence: true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum: 30 }
    validates :password, presence: true, length: { minimum: 8 }
    validates :email, presence: true, length: {maximum: 255},
                                        format: {with: VALID_EMAIL_REGEX},
                                        uniqueness: {case_sensitive: true}

    

    has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper

    private
        def require_logged_in_user
            unless user_signed_in?
                flash[:danger] = "Faça login para continuar"
                redirect_to entrar_path
            end
        end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = current_user.contacts 
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to contacts_path(user)
    else
      flash.now[:danger] = "email ou senha invalida"
      render 'new'
    end
  end 
  def destroy
    sign_out
    flash[:success] = "logout com sucesso"
    redirect_to entrar_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index #for each page has one function here "convertion over configuration"
        @name = "Michel"
    end

    def about
    end

    def contact
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save   
        flash[:success] = "Usuario salvo com sucesso"
        redirect_to root_url
        else
            render 'new'
        end
    end

    private
     def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        session[:user_id] = user.id
    end

    def sign_out
        session.delete(:user_id)
    end

    def current_user
        @current_user || User.find_by(id:session[:user_id])
    end

    def user_signed_in?
        !current_user.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">

      <li class="nav-item">
        <%= link_to "Contatos", contato_path, class: 'nav-link px-2 text-muted'%>
      </li>
      <li class="nav-item">
        <%= link_to "Sobre", sobre_path, class: 'nav-link px-2 text-muted'%>
      </li>
    </ul>
    <p class="text-center text-muted">© 2022 Contact List</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><i class="bi bi-person-lines-fill"></i>  Contact List</a>
    <div class="nav navbar-nav navbar-right" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <%if !user_signed_in?%>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Login</a>
        </li>

        <li class="nav-item">
         <%=link_to "Nova Conta", new_user_path, class:"nav-link"%>
        </li>

        <%else%>
          <%=link_to "Sair", sair_path, method: :delete, class:"nav-link"%>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsContactList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <div>
       <% flash.each do |message_type, message| %>
       <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
         <%= message %>
       <% end %>
     <% end %>
  </div>

  <body>
  
    <%= render "layouts/header" %> <!-- this add partial codes-->
    
    <div class="container">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  <div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>Sobre</h1>

<p>
Contact List - 2022
<p>

app/views/static_pages/contact.html.erb
<h1>Contatos</h1>

<p>
<a href= github.com/michloliveira>GitHub<a>
</p>

app/views/static_pages/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="jumbotron">
  <h1>Rails Contact List</h1>
  <p>
    Lista de contatos em qualquer lugar
  </p>
  <p>
    <%=link_to "Nova Conta", new_user_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      
    <%end%>

    <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div>
        <%= form.submit 'Cadastrar', class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/users/index.html.erb
<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<div class = "col-xs-12">
<h1>Cadastre-se</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>